### ISSUE TITLE
Tool can not be used in Robot Framework 3.1 + Python 3.5

### ISSUE THREAD

**Issue by stonerzju** [robotframework/DbBot#24]
I am new to this tool but found it quite useful.
But when I try to parse the report which generated by Robot Framework 3.1 + Python 3.5, It failed to run.

agilis@ubuntu:~/Code/Agilis/Tests/SLC_MIT/TestReport$ python -m dbbot.run output.xml 
Traceback (most recent call last):
  File "/home/agilis/miniconda3/envs/py35/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/agilis/miniconda3/envs/py35/lib/python3.5/runpy.py", line 153, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 799, in get_code
  File "<frozen importlib._bootstrap_external>", line 759, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/agilis/miniconda3/envs/py35/lib/python3.5/site-packages/dbbot/run.py", line 43
    except DataError, message:
                    ^
SyntaxError: invalid syntax

**Comment by pekkaklarck** [comment]
It seems the code is not Python 3 compatible. This project is currently unmaintained so don't know when, if ever, the problem is fixed.

**Comment by tiwarshr** [comment]
i was facing the similar issue. it seems that with dbbot ,we need to install dbbot-sqlalchemy too.
just install it via pip using pip install dbbot-sqlalchemy,it should work .
Worked for me .
Happy Testing !!

**Comment by Tattoo** [comment]
[dbbot-sqlalchemy](https://pypi.org/project/dbbot-sqlalchemy/) is separate fork of this project that seems to be actively maintained, has Python 3 support, and supports more databases than sqlite

I would recommend everyone to check it out
